# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-11 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_mia_app', '0002_dog_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='adopted',
            field=models.BooleanField(default=False, max_length=3),
        ),
    ]
